# data
data:
  instruct_data: ""
  data: ""
  eval_instruct_data: ""  # Optionally fill

# model
model_id_or_path: ".../open-mistral-7b"  # Change to downloaded path
lora:
  rank: 48

# optim
seq_len: 4096
batch_size: 1
max_steps: 600
optim:
  lr: 6.e-5
  weight_decay: 0.1
  pct_start: 0.05

# other
seed: 0
log_freq: 1
eval_freq: 100
no_eval: False
ckpt_freq: 100
no_eval: True
run_dir: ""
save_adapters: True  # save only trained LoRA adapters. Set to `False` to merge LoRA adapter into the base model and save full fine-tuned model

wandb:
  project: "" # your wandb project name
  run_name: "" # your wandb run name
  key: "" # your wandb api key
  offline: False
